### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\ufeff' in position #

### ISSUE THREAD

**Issue by Ahmed-Shibl** [MicrobeLab/DeepMicrobes#21]
Hi DeepMicrobes developers and users,
I'm excited to start using this tool on my dataset but I'm running into an error at the installation testing step. 

Here is the command I run:
`/scratch/gencore/software/DeepMicrobes/DeepMicrobes.py --helpfull`

and here is the output I get:
```
2022-09-18 21:42:58.116424: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA

       USAGE: /scratch/gencore/software/DeepMicrobes/DeepMicrobes.py [flags]
flags:
Traceback (most recent call last):
  File "/scratch/gencore/software/DeepMicrobes/DeepMicrobes.py", line 365, in <module>
    absl_app.run(main)
  File "/scratch/gencore/conda3/envs/deepmicrobes/lib/python3.6/site-packages/absl/app.py", line 273, in run
    args = _run_init(sys.argv if argv is None else argv)
  File "/scratch/gencore/conda3/envs/deepmicrobes/lib/python3.6/site-packages/absl/app.py", line 324, in _run_init
    args = _register_and_parse_flags_with_usage(argv=argv)
  File "/scratch/gencore/conda3/envs/deepmicrobes/lib/python3.6/site-packages/absl/app.py", line 204, in _register_and_parse_flags_with_usage
    args_to_main = parse_flags_with_usage(original_argv)
  File "/scratch/gencore/conda3/envs/deepmicrobes/lib/python3.6/site-packages/absl/app.py", line 159, in parse_flags_with_usage
    return FLAGS(args)
  File "/scratch/gencore/conda3/envs/deepmicrobes/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 623, in __call__
    unknown_flags, unparsed_args = self._parse_args(args, known_only)
  File "/scratch/gencore/conda3/envs/deepmicrobes/lib/python3.6/site-packages/absl/flags/_flagvalues.py", line 759, in _parse_args
    flag.parse(value)
  File "/scratch/gencore/conda3/envs/deepmicrobes/lib/python3.6/site-packages/absl/app.py", line 129, in parse
    usage(writeto_stdout=True)
  File "/scratch/gencore/conda3/envs/deepmicrobes/lib/python3.6/site-packages/absl/app.py", line 377, in usage
    stdfile.write(flag_str)
UnicodeEncodeError: 'ascii' codec can't encode character '\ufeff' in position 4996: ordinal not in range(128)
```

I haven't worked with a deep learning-based computational framework before so I'm not quite sure what I'm looking at here. Please let me know if you'd want more information from my side. Thanks!

**Comment by MicrobeLab** [comment]
Hi, could you please let me known how you performed the installation? And did the error occur with release v1.0.0? Thanks.

**Comment by jayramr** [comment]
Thanks @Ahmed-Shibl for raising the issue. 

Hi @MicrobeLab the installation is performed using conda which installed from "install.yml" file.

**Comment by MicrobeLab** [comment]
Is the issue related to the update of setup.py?

**Comment by jayramr** [comment]
@MicrobeLab this is not related to setup.py. I'm still testing the setup.py on my another server. I will update the progress on the other ticket.

I suspect this is related to OS/system side configuration. 
```
Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
```

**Comment by MicrobeLab** [comment]
Hi I have not seen this error before. You could try running the command without the --helpfull and see if the error is reproduced.
