### ISSUE TITLE
How should I run this model in single-end mode?

### ISSUE THREAD

**Issue by stargazer-dot** [MicrobeLab/DeepMicrobes#32]

**Comment by MicrobeLab** [comment]
For single-end reads, only one fastq file will need to be interleaved and in the model codes the prediction should be averaged across 2 samples rather than 4 samples.

**Comment by Gayathri142** [comment]
Hello, can you please elaborate a bit more about this? So when trying to generate tfrec for single ended data, what would the input be? Right now it takes a -f and -r as input. When I try to give just one file it throws an error. Can you paste the command for single end data here? To generate tfrec for our sample data

**Comment by MicrobeLab** [comment]
Hi, it might be a good choice to directly run the python script for converting data to tfrec: seq2tfrec_kmer.py \
	--input_seq={} --output_tfrec={}.${kmer}mer.tfrec \
	--vocab=${vocab} --kmer=${kmer} \
	--seq_type=${seq_type}

**Comment by Gayathri142** [comment]
Thank you. I have generated a tfrec file for single-end sample using seq2tfrec_kmer.py.
However, when I try to run 'predict_DeepMicrobes.sh' it gives me an error saying the paired-end file is missing. Can you please tell me how to perform prediction on single-end tfrec files

**Comment by MicrobeLab** [comment]
Hi, could you please give the command that you ran 'predict_DeepMicrobes.sh' and the exact error message?

**Comment by ChillarAnand** [comment]
> seq2tfrec_kmer.py

It is failing with the following error.


```
I1020 12:31:34.288781 139676691638080 tf_logging.py:115] Running local_init_op.
I1020 12:31:34.295372 139676691638080 tf_logging.py:115] Done running local_init_op.

Traceback (most recent call last):
  File "/home/anand/projects/sandbox/DeepMicrobes/DeepMicrobes.py", line 365, in <module>
    absl_app.run(main)
  File "/home/anand/miniforge3/envs/DeepMicrobes/lib/python3.6/site-packages/absl/app.py", line 278, in run
    _run_main(main, args)
  File "/home/anand/miniforge3/envs/DeepMicrobes/lib/python3.6/site-packages/absl/app.py", line 239, in _run_main
    sys.exit(main(argv))
  File "/home/anand/projects/sandbox/DeepMicrobes/DeepMicrobes.py", line 348, in main
    flags.FLAGS.translate)
  File "/home/anand/projects/sandbox/DeepMicrobes/models/format_prediction.py", line 89, in paired_report
    batch_prob = average_paired_end(batch_prob, num_classes)
  File "/home/anand/projects/sandbox/DeepMicrobes/models/format_prediction.py", line 14, in average_paired_end
    prob_matrix = np.mean(np.reshape(prob_matrix, (-1, 4, num_classes)), axis=1)
  File "/home/anand/miniforge3/envs/DeepMicrobes/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 232, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/home/anand/miniforge3/envs/DeepMicrobes/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 57, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 222945 into shape (4,2505)
paste: output_p.category_paired.txt: No such file or directory
rm: cannot remove 'output_p.category_paired.txt': No such file or directory
rm: cannot remove 'output_p.prob_paired.txt': No such file or directory
Result: output_p.result.txt
```

**Comment by MicrobeLab** [comment]
You can change the running mode to predict_single_class, the default is predict_paired_class.

**Comment by ChillarAnand** [comment]
@MicrobeLab Thank you. That worked.

Do you provide the models that you have used in the paper?
